version: '3.8'

services:
  app:
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000-3007:3000-3007"
    volumes:
      - ./src/:/app
      # - ./data/chat.db:/app/chat.db
    environment:
      - NODE_ENV=production
    restart: unless-stopped

volumes:
  node_modules:
